language: r

matrix:
  include:
    - r: oldrel
      os: linux
      dist: trusty
      sudo: false
    - r: release
      os: linux
      dist: trusty
      sudo: false
    - r: devel
      os: linux
      dist: trusty
      sudo: false
    - r: release
      os: osx

warnings_are_errors: true

env:
  global:
    - TEST_PVM=TRUE

after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'