
if (Sys.getenv("TEST_PVM_INIT") != "TRUE") quit("no")
library(remotes)
library(pvm)
lib.loc <- tempfile(fileext = ".lib")
dir.create(lib.loc)
remotes::install_url("https://github.com/wush978/pvmtest/archive/master.zip", lib = lib.loc)
export.packages(pvm.path <- tempfile(fileext = ".yml"), lib.loc = lib.loc)
yaml::yaml.load_file(pvm.path)
file.copy(pvm.path, "pvm/url-pvmtest-master.yml")
